### PR TITLE
allow passing client UID to faraday configuration

### PR DESCRIPTION
**Pull request by Wlojtek**
allow passing client UID to faraday client

### CODE REVIEW

**Comment by Wlojtek** [comment]
Hi Han (@han8909227)
Oh if that is enough on your end. Then I'm happy to ignore this PR.

Wojtek

**Comment by Wlojtek** [comment]
ignore

**Comment by Wlojtek** [comment]
@han8909227 HI there! I would like to reopen this PR. We need `X-Avalara-UID` to be attached into each request. We need it to pass Avalara certification.

**Comment by ted-spence-avalara** [comment]
Hi Wlojtek -

We've checked with the partner launch team, and this UID is currently in the process of being defined.  The API does not yet actually support it, so we aren't looking to include it into the SDK yet.

**Comment by Wlojtek** [comment]
@ted-spence-avalara okay https://i.kym-cdn.com/entries/icons/original/000/003/617/OkayGuy.jpg

**Comment by Wlojtek** [comment]
@ted-spence-avalara how about now? is it good time to introduce it?

**Pull request closed without merging**
