### PR TITLE
Fix syntax of transaction in example code

### PR DESCRIPTION
**Pull request by zreisman**
Current syntax is invalid.

### CODE REVIEW

**Comment by marcus** [comment]
This hash syntax has been supported in ruby since 1.9. Curious why you believe it’s inavalid.

**Comment by joelvh** [comment]
Maybe because the keys are symbols and he wants them to be strings?

**Comment by zreisman** [comment]
A trailing colon instead of a hash rocket is valid, however it isn't valid combined with the quote. `"key": "value"`

screen shot 2018-10-18 at 10 52 18 am

**Comment by joelvh** [comment]
Ah, I see what you were pointing out -- on my phone notification I saw the first couple lines, which have symbol keys.

**Comment by marcus** [comment]
Gotcha. Javascript has corrupted me :) Thanks for the clarification.

**Pull request merged**
